version: 2

jobs:
  check-policies:
    docker:
      - image: cloudcustodian/c7n
    steps:
      - checkout
      - run: custodian run --verbose --output-dir ./output policy.yml

workflows:
  version: 2
  deploy:
    jobs:
      - check-policies
