version: 2

jobs:
  run-policies:
    docker:
      - image: cloudcustodian/c7n:0.8.44.2
    steps:
      - checkout
      # Regions are explicitly listed because running against all regions fails
      # on region ap-east-1.
      # See https://github.com/boto/boto3/issues/2022
      - run: >
          custodian run 
          --output-dir ./output-<< parameters.account >> 
          --region ap-northeast-1 
          --region ap-northeast-2 
          --region ap-south-1 
          --region ap-southeast-1 
          --region ap-southeast-2 
          --region ca-central-1 
          --region eu-central-1 
          --region eu-north-1 
          --region eu-west-1 
          --region eu-west-2 
          --region eu-west-3 
          --region sa-east-1 
          --region us-east-1 
          --region us-east-2 
          --region us-west-1 
          --region us-west-2 
          policy-<< parameters.account >>.yml
      - store_artifacts:
          path: ./output-<< parameters.account >>
      - persist_to_workspace:
          root: ./
          paths: [output-<< parameters.account >>/]
  check-policies:
    docker:
      - image: node:12
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: node check-output.js output-<< parameters.account >>

workflows:
  version: 2
  check-policies:
    jobs:
      - run-policies:
          name: run-policies-training
          account: training
      - check-policies:
          account: training
          requires:
            - run-policies-training
  check-policies-nightly:
    jobs:
      - run-policies:
          name: run-policies-training
          account: training
      - check-policies:
          account: training
          requires:
            - run-policies-training
    triggers:
      - schedule:
          cron: 0 7 * * 1-5
          filters:
            branches:
              only: master
